import "./styles.css";
import pfp from "./assets/images/pfp.png";
import github from "./assets/icons/github.svg";
import linkedin from "./assets/icons/linkedin.svg";
import x from "./assets/icons/x.svg";
import externalLink from "./assets/icons/external-link.svg";
import placeholder from "./assets/images/placeholder.png";
import pic2 from "./assets/images/pic2.png";
import phoneIcon from "./assets/icons/phone.svg";
import emailIcon from "./assets/icons/mail.svg";
